### ISSUE TITLE
Some adaptations for Python 3

### ISSUE THREAD

**Issue by lantonov** [vondele/FishTestWatch#1]
**file ftw**
line 55
```python
f = urllib.request.urlopen(sys.argv[1])
```
line 63
```python
line = list(filter(None,re.split("[a-zA-Z: ()\[\],\n]+",line)))
```
line 66
```python
print("No Data yet!")
```

**Comment by lantonov** [comment]
Nice tool!
![image](https://user-images.githubusercontent.com/6498222/32996185-5d7701ae-cd88-11e7-8394-e57d567bc3af.png)
LLR and LOS express the same thing but in different scales

**Comment by vondele** [comment]
Thanks, the version now should be python 2 & 3 compatible.
